# Generated by Django 4.0.2 on 2022-02-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0005_post_ti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ti',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
