# Generated by Django 4.0.2 on 2022-02-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_ti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ti',
            field=models.CharField(max_length=127, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=127),
        ),
    ]
