# Generated by Django 4.0.2 on 2022-02-11 11:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0007_alter_post_ti_alter_post_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='ti',
            new_name='slug',
        ),
    ]
