# Generated by Django 4.0.2 on 2022-02-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0008_rename_ti_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=127, unique=True),
        ),
    ]
