# Generated by Django 4.0.2 on 2022-02-23 14:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='subscription_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
