# Generated by Django 4.0.2 on 2022-02-25 14:52

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0022_subscriber_subscription_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_picture',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.post_directory_path),
        ),
    ]
